return {
  categories = {
    { id = "run_control", group = "控制台", icon = "运", name = "运行控制", desc = "执行调试开关、刷新、回溯、重开和楼层重置等运行命令。", shortDesc = "调试、刷新与运行控制", eyebrow = "RUN CONTROL" },
    { id = "command_reference", group = "控制台", icon = "令", name = "命令参考", desc = "官方命令语法参考；参数命令需按 C 补全，禁用项只供查阅。", shortDesc = "官方语法与安全状态", eyebrow = "COMMAND REFERENCE" },
    { id = "custom_commands", group = "控制台", icon = "自", name = "自定义命令", desc = "高级原始命令透传；可命名、搜索、收藏、编辑和删除，风险由用户承担。", shortDesc = "高级原始命令透传", eyebrow = "CUSTOM COMMANDS" },
  },
  commands = {
    { commandId = "rewind", cat = "run_control", name = "回溯房间", en = "Rewind", icon = "回", tier = "S", desc = "回到上一个房间状态。", cmd = "rewind" },
    { commandId = "restart", cat = "run_control", name = "重新开始", en = "Restart", icon = "R", tier = "S", desc = "以当前角色重新开始一局。", cmd = "restart" },
    { commandId = "reseed", cat = "run_control", name = "重生成本层", en = "Reseed Floor", icon = "种", tier = "S", desc = "重新生成当前楼层。", cmd = "reseed" },
    { commandId = "debug", cat = "run_control", name = "显示持有物", en = "Debug Flag 12", icon = "12", tier = "A", desc = "显示持有收藏品和临时收藏品效果；再次执行可关闭。", cmd = "debug 12" },
    { commandId = "debug", cat = "run_control", name = "网格碰撞点", en = "Debug Flag 13", icon = "13", tier = "A", desc = "显示实体网格碰撞点；再次执行可关闭。", cmd = "debug 13" },
    { commandId = "costumetest", cat = "run_control", name = "随机外观", en = "Costume Test", icon = "装", tier = "A", desc = "为角色添加随机外观，不给予对应道具。", cmd = "costumetest" },
    { commandId = "clearseeds", cat = "run_control", name = "清除特殊种子", en = "Clear Seeds", icon = "清", tier = "A", desc = "清除当前局的特殊种子效果。", cmd = "clearseeds" },
    { commandId = "restock", cat = "run_control", name = "重置房间底座", en = "Restock", icon = "货", tier = "A", desc = "重置当前房间内商店或道具底座内容。", cmd = "restock" },
    { commandId = "reloadwisps", cat = "run_control", name = "刷新魂火", en = "Reload Wisps", icon = "火", tier = "A", desc = "刷新美德书魂火与深渊蝗虫。", cmd = "reloadwisps" },

    { commandId = "spawn", cat = "command_reference", name = "生成实体", en = "spawn", icon = "生", tier = "A", desc = "参数参考：实体类型.变体.子类型.精英类型。", catalogAction = "manual" },
    { commandId = "goto", cat = "command_reference", name = "跳转房间", en = "goto", icon = "房", tier = "S", desc = "参数参考：按房间类别、ID或维度立即跳转到目标房间。", catalogAction = "manual" },
    { commandId = "stage", cat = "command_reference", name = "跳转楼层", en = "stage", icon = "层", tier = "S", desc = "参数参考：楼层 1–13 加可选 a–d；仅允许当前模式实际存在的楼层组合。", catalogAction = "manual" },
    { commandId = "gridspawn", cat = "command_reference", name = "生成网格实体", en = "gridspawn", icon = "格", tier = "A", desc = "参数参考：在当前房间生成指定网格实体。", catalogAction = "manual" },
    { commandId = "debug", cat = "command_reference", name = "调试标志", en = "debug", icon = "调", tier = "A", desc = "参数参考：切换指定调试标志。", catalogAction = "manual" },
    { commandId = "giveitem", cat = "command_reference", name = "给予物品", en = "giveitem / g", icon = "给", tier = "A", desc = "参数参考：给予收藏品、饰品、胶囊或卡牌。", catalogAction = "manual" },
    { commandId = "remove", cat = "command_reference", name = "移除物品", en = "remove / r", icon = "移", tier = "A", desc = "参数参考：移除指定收藏品或饰品。", catalogAction = "manual" },
    { commandId = "restart", cat = "command_reference", name = "指定角色重开", en = "restart", icon = "角", tier = "S", desc = "参数参考：角色编号必须为官方 0–40。", catalogAction = "manual" },
    { commandId = "seed", cat = "command_reference", name = "指定种子", en = "seed", icon = "种", tier = "S", desc = "参数参考：输入大写的 XXXX XXXX 种子并开始新流程。", catalogAction = "manual" },
    { commandId = "challenge", cat = "command_reference", name = "开始挑战", en = "challenge", icon = "挑", tier = "S", desc = "参数参考：仅允许当前游戏版本中存在的挑战编号。", catalogAction = "manual" },
    { commandId = "combo", cat = "command_reference", name = "给予组合", en = "combo", icon = "组", tier = "A", desc = "参数参考：从指定物品池给予指定数量的随机物品。", catalogAction = "manual" },
    { commandId = "playsfx", cat = "command_reference", name = "播放音效", en = "playsfx", icon = "声", tier = "A", desc = "参数参考：播放指定音效 ID。", catalogAction = "manual" },
    { commandId = "curse", cat = "command_reference", name = "设置诅咒", en = "curse", icon = "咒", tier = "A", desc = "参数参考：诅咒位掩码限制为 0–255。", catalogAction = "manual" },
    { commandId = "metro", cat = "command_reference", name = "节拍器测试", en = "metro", icon = "拍", tier = "A", desc = "参数参考：开发调试用节拍器命令。", catalogAction = "manual" },
    { commandId = "delirious", cat = "command_reference", name = "精神错乱形态", en = "delirious", icon = "乱", tier = "A", desc = "参数参考：设置精神错乱的 Boss 形态。", catalogAction = "manual" },

    { commandId = "listcollectibles", cat = "command_reference", name = "列出收藏品", en = "listcollectibles", icon = "表", tier = "D", desc = "输出只会显示在原生控制台，本界面不提供输出页。", catalogAction = "disabled" },
    { commandId = "copy", cat = "command_reference", name = "复制控制台输出", en = "copy", icon = "复", tier = "D", desc = "依赖原生控制台及系统剪贴板，本界面禁用。", catalogAction = "disabled" },
    { commandId = "clear", cat = "command_reference", name = "清空控制台输出", en = "clear", icon = "清", tier = "D", desc = "只影响原生控制台输出，本界面禁用。", catalogAction = "disabled" },
    { commandId = "luamem", cat = "command_reference", name = "Lua 内存输出", en = "luamem", icon = "内", tier = "D", desc = "只向原生控制台输出诊断信息，本界面禁用。", catalogAction = "disabled" },
    { commandId = "testbosspool", cat = "command_reference", name = "Boss 池输出", en = "testbosspool", icon = "首", tier = "D", desc = "只向原生控制台输出测试结果，本界面禁用。", catalogAction = "disabled" },
    { commandId = "lua", cat = "command_reference", name = "执行 Lua", en = "lua / l", icon = "禁", tier = "D", desc = "可执行任意代码，工坊版安全禁用。", catalogAction = "disabled" },
    { commandId = "luarun", cat = "command_reference", name = "运行 Lua 文件", en = "luarun", icon = "禁", tier = "D", desc = "可执行外部 Lua 文件，工坊版安全禁用。", catalogAction = "disabled" },
    { commandId = "luamod", cat = "command_reference", name = "重载 Mod Lua", en = "luamod", icon = "禁", tier = "D", desc = "会重载 Mod 代码和状态，工坊版安全禁用。", catalogAction = "disabled" },
    { commandId = "achievement", cat = "command_reference", name = "修改成就", en = "achievement", icon = "禁", tier = "D", desc = "可能修改持久进度，工坊版安全禁用。", catalogAction = "disabled" },
    { commandId = "prof", cat = "command_reference", name = "性能分析器", en = "prof", icon = "禁", tier = "D", desc = "开发器内部进程命令，工坊版禁用。", catalogAction = "disabled" },
    { commandId = "fullrestart", cat = "command_reference", name = "完整重启", en = "fullrestart", icon = "禁", tier = "D", desc = "会重启游戏进程，工坊版安全禁用。", catalogAction = "disabled" },
    { commandId = "quit", cat = "command_reference", name = "退出游戏", en = "quit", icon = "禁", tier = "D", desc = "会退出游戏进程，工坊版安全禁用。", catalogAction = "disabled" },
    { commandId = "macro", cat = "command_reference", name = "执行宏", en = "macro / m", icon = "禁", tier = "D", desc = "可间接执行多条未知命令，工坊版安全禁用。", catalogAction = "disabled" },
    { commandId = "repeat", cat = "command_reference", name = "重复上一命令", en = "repeat", icon = "禁", tier = "D", desc = "执行目标和次数不可可靠约束，工坊版安全禁用。", catalogAction = "disabled" },
  },
}
