-- Generated from the v1.3.0 curated catalog. Do not edit by hand.
return {
  categories = {
    { id = "featured", group = "精选", icon = "✦", name = "常用精选", desc = "只显示你主动收藏的物品。", eyebrow = "MY FAVORITES" },
    { id = "all_items", group = "物品", icon = "全", name = "全部收藏品", desc = "读取游戏当前版本的完整收藏品表；精选与高质量收藏品优先。", eyebrow = "COLLECTIBLES" },
    { id = "trinkets", group = "物品", icon = "饰", name = "饰品", desc = "官方基础饰品；给予后可移除饰品本体。", eyebrow = "TRINKETS" },
    { id = "cards", group = "物品", icon = "卡", name = "卡牌/符文", desc = "官方卡牌、符文、逆位牌和魂石；只支持单次给予。", eyebrow = "CARDS & RUNES" },
    { id = "pills", group = "物品", icon = "药", name = "胶囊效果", desc = "官方基础胶囊效果；只支持单次给予。", eyebrow = "PILL EFFECTS" },
    { id = "damage", group = "道具", icon = "刃", name = "输出核心", desc = "伤害、射击方式与高强度叠加核心。", eyebrow = "DAMAGE & TEARS" },
    { id = "defense", group = "道具", icon = "盾", name = "生存防御", desc = "护盾、减伤、免疫与容错道具。", eyebrow = "SURVIVAL" },
    { id = "economy", group = "道具", icon = "$", name = "资源经济", desc = "商店、掉落与资源成长道具。", eyebrow = "ECONOMY" },
    { id = "explore", group = "道具", icon = "图", name = "地图探索", desc = "地图显示、隐藏房与房间移动工具。", eyebrow = "NAVIGATION" },
    { id = "active", group = "道具", icon = "骰", name = "主动神器", desc = "重随、回溯、重开与改变流程的强力主动道具。", eyebrow = "ACTIVE ITEMS" },
    { id = "familiar", group = "道具", icon = "伴", name = "跟班军团", desc = "输出、格挡与续航型跟班。", eyebrow = "FAMILIARS" },
    { id = "fun", group = "道具", icon = "乱", name = "趣味组合", desc = "适合测试构筑与制造夸张联动。", eyebrow = "CHAOS LAB" },
    { id = "debug", group = "控制台", icon = "⚙", name = "调试能力", desc = "无敌、高伤、无限充能与信息显示开关。再次点击同一 debug 命令可关闭。", eyebrow = "DEBUG FLAGS" },
    { id = "supply", group = "控制台", icon = "+", name = "即时补给", desc = "生成资源、回复与当前房间辅助。", eyebrow = "SUPPLY DROP" },
    { id = "stage", group = "控制台", icon = "门", name = "楼层跳转", desc = "按当前模式显示安全楼层：正常模式 45 项，贪婪模式 7 项。", eyebrow = "STAGE WARP" },
  },
  items = {
    { id = 182, cat = "damage", name = "圣心", en = "Sacred Heart", tier = "S", icon = "心", desc = "高额伤害倍率、自追踪与生命上限，最稳定的顶级输出核心。", hot = 1 },
    { id = 331, cat = "damage", name = "神性", en = "Godhead", tier = "S", icon = "神", desc = "追踪泪弹附带持续伤害光环，清图与对 Boss 都很强。", hot = 1 },
    { id = 118, cat = "damage", name = "硫磺火", en = "Brimstone", tier = "S", icon = "硫", desc = "蓄力发射贯穿房间的血激光，经典强力射击方式。", hot = 1 },
    { id = 114, cat = "damage", name = "妈妈的刀", en = "Mom's Knife", tier = "S", icon = "刀", desc = "将泪弹替换为蓄力飞刀，近远距离都拥有极高伤害。", hot = 1 },
    { id = 678, cat = "damage", name = "剖腹产", en = "C Section", tier = "S", icon = "胎", desc = "发射可追踪的胎儿弹体，联动丰富且基础强度极高。", hot = 1 },
    { id = 395, cat = "damage", name = "科技 X", en = "Tech X", tier = "S", icon = "X", desc = "蓄力发射激光圆环，贯穿、范围大并能穿透障碍。", hot = 1 },
    { id = 531, cat = "damage", name = "血泪症", en = "Haemolacria", tier = "S", icon = "血", desc = "泪弹落地后分裂爆开，极大提高爆发与覆盖范围。", hot = 1 },
    { id = 169, cat = "damage", name = "独眼巨人", en = "Polyphemus", tier = "S", icon = "眼", desc = "巨额伤害倍率，射速下降但单发伤害非常夸张。", hot = 1 },
    { id = 562, cat = "damage", name = "谷底石", en = "Rock Bottom", tier = "S", icon = "石", desc = "锁定已获得的最高属性数值，构筑上限极高。", hot = 1 },
    { id = 691, cat = "damage", name = "神圣宝珠", en = "Sacred Orb", tier = "S", icon = "珠", desc = "改善后续道具质量，降低低质量道具出现概率。", hot = 1 },
    { id = 689, cat = "damage", name = "故障王冠", en = "Glitched Crown", tier = "S", icon = "冠", desc = "道具在多个选项间快速切换，可大幅提高获取顶级道具的机会。", hot = 1 },
    { id = 12, cat = "damage", name = "魔法蘑菇", en = "Magic Mushroom", tier = "A", icon = "菇", desc = "全属性提升并提供伤害倍率，是泛用性极好的强化。" },
    { id = 4, cat = "damage", name = "蟋蟀的头", en = "Cricket's Head", tier = "A", icon = "猫", desc = "提高伤害并提供强力伤害倍率，简单直接。" },
    { id = 415, cat = "damage", name = "圣光之冠", en = "Crown of Light", tier = "A", icon = "冠", desc = "满红心时大幅提高伤害与射程。" },
    { id = 245, cat = "damage", name = "20/20", en = "20/20", tier = "A", icon = "双", desc = "一次发射两颗泪弹，是可靠的多发输出道具。" },
    { id = 313, cat = "defense", name = "神圣斗篷", en = "Holy Mantle", tier = "S", icon = "衣", desc = "每个房间抵挡一次伤害，提供顶级稳定容错。", hot = 1 },
    { id = 108, cat = "defense", name = "圣饼", en = "The Wafer", tier = "S", icon = "饼", desc = "将大部分伤害降低为半颗心，后期生存能力极强。", hot = 1 },
    { id = 581, cat = "defense", name = "灵魂苍蝇", en = "Psy Fly", tier = "S", icon = "蝇", desc = "自动追踪并格挡敌方弹幕，对弹幕 Boss 尤其强。", hot = 1 },
    { id = 223, cat = "defense", name = "纵火狂", en = "Pyromaniac", tier = "S", icon = "火", desc = "免疫爆炸，并可通过爆炸回复红心。", hot = 1 },
    { id = 375, cat = "defense", name = "寄居骷髅帽", en = "Host Hat", tier = "A", icon = "帽", desc = "免疫爆炸并有概率格挡敌方弹幕。" },
    { id = 210, cat = "defense", name = "啃过的叶子", en = "Gnawed Leaf", tier = "A", icon = "叶", desc = "静止一段时间后进入无敌，适合与自动攻击跟班配合。" },
    { id = 81, cat = "defense", name = "嗝屁猫", en = "Dead Cat", tier = "A", icon = "猫", desc = "获得九条命；会把红心上限调整为一颗。" },
    { id = 232, cat = "defense", name = "秒表", en = "Stop Watch", tier = "A", icon = "表", desc = "永久减缓大多数敌人和敌方弹幕。" },
    { id = 242, cat = "defense", name = "耻辱面具", en = "Infamy", tier = "A", icon = "面", desc = "有概率从角色面朝方向格挡伤害。" },
    { id = 64, cat = "economy", name = "Steam 大促", en = "Steam Sale", tier = "S", icon = "折", desc = "商店价格减半，越早拿到收益越高。", hot = 1 },
    { id = 203, cat = "economy", name = "乞丐的包袱", en = "Humbling Bundle", tier = "S", icon = "双", desc = "多数基础掉落会成对出现，显著提高资源量。", hot = 1 },
    { id = 241, cat = "economy", name = "地狱契约", en = "Contract From Below", tier = "S", icon = "契", desc = "大幅提高房间清理后的掉落数量。", hot = 1 },
    { id = 716, cat = "economy", name = "店主的袋子", en = "Keeper's Sack", tier = "S", icon = "袋", desc = "在商店花钱会持续提高属性，成长性很强。", hot = 1 },
    { id = 416, cat = "economy", name = "深口袋", en = "Deep Pockets", tier = "A", icon = "袋", desc = "硬币上限提高到 999，并改善空房掉落。" },
    { id = 424, cat = "economy", name = "袋中袋", en = "Sack Head", tier = "A", icon = "袋", desc = "掉落有机会替换为装有多种资源的袋子。" },
    { id = 429, cat = "economy", name = "店主的头", en = "Head of the Keeper", tier = "A", icon = "金", desc = "泪弹击中敌人时有概率掉落硬币。" },
    { id = 109, cat = "economy", name = "钱就是力量", en = "Money = Power", tier = "A", icon = "$", desc = "持有的硬币越多，伤害越高。" },
    { id = 249, cat = "economy", name = "选择？", en = "There's Options", tier = "A", icon = "?", desc = "Boss 房奖励出现两个选择。" },
    { id = 414, cat = "economy", name = "更多选择", en = "More Options", tier = "A", icon = "+", desc = "宝箱房道具出现两个选择。" },
    { id = 21, cat = "explore", name = "指南针", en = "The Compass", tier = "A", icon = "针", desc = "在地图上显示特殊房间图标。", hot = 1 },
    { id = 54, cat = "explore", name = "藏宝图", en = "Treasure Map", tier = "A", icon = "图", desc = "显示当前楼层的房间布局。", hot = 1 },
    { id = 246, cat = "explore", name = "蓝地图", en = "Blue Map", tier = "A", icon = "蓝", desc = "在地图上显示隐藏房与超级隐藏房。", hot = 1 },
    { id = 76, cat = "explore", name = "X 光透视", en = "X-Ray Vision", tier = "A", icon = "X", desc = "自动打开大多数隐藏房入口。", hot = 1 },
    { id = 580, cat = "explore", name = "红钥匙", en = "Red Key", tier = "S", icon = "钥", desc = "在合适墙面开启红房间，探索隐藏版图。", hot = 1 },
    { id = 419, cat = "explore", name = "传送 2.0", en = "Teleport 2.0", tier = "A", icon = "传", desc = "按探索顺序传送到未进入的房间，并可抵达特殊房。" },
    { id = 91, cat = "explore", name = "探险帽", en = "Spelunker Hat", tier = "A", icon = "帽", desc = "显示相邻房间类型，并帮助发现隐藏房。" },
    { id = 175, cat = "explore", name = "爸爸的钥匙", en = "Dad's Key", tier = "A", icon = "钥", desc = "打开当前房间的门，也能处理部分特殊门。" },
    { id = 84, cat = "explore", name = "我们需要深入挖掘", en = "We Need to Go Deeper!", tier = "A", icon = "铲", desc = "生成通往下一层的活板门。" },
    { id = 105, cat = "active", name = "D6", en = "The D6", tier = "S", icon = "6", desc = "重置房间内的道具，是最泛用的主动道具之一。", hot = 1 },
    { id = 489, cat = "active", name = "无限面骰", en = "D Infinity", tier = "S", icon = "∞", desc = "可切换多种骰子效果，功能极其全面。", hot = 1 },
    { id = 723, cat = "active", name = "倒转骰子", en = "Spindown Dice", tier = "S", icon = "↘", desc = "把道具 ID 向下重置，可稳定获取特定强力道具。", hot = 1 },
    { id = 636, cat = "active", name = "R 键", en = "R Key", tier = "S", icon = "R", desc = "保留当前构筑重新开始一局，适合延长路线。", hot = 1 },
    { id = 628, cat = "active", name = "死亡证明", en = "Death Certificate", tier = "S", icon = "证", desc = "进入包含全部道具的区域，可任选一件。", hot = 1 },
    { id = 622, cat = "active", name = "创世记", en = "Genesis", tier = "S", icon = "创", desc = "重构身上道具，并在特殊区域重新选择构筑。", hot = 1 },
    { id = 477, cat = "active", name = "虚空", en = "Void", tier = "A", icon = "空", desc = "吞噬道具：主动效果合并，被动道具转化为属性。" },
    { id = 476, cat = "active", name = "D1", en = "The D1", tier = "A", icon = "1", desc = "复制房间中的随机掉落物。" },
    { id = 422, cat = "active", name = "发光沙漏", en = "Glowing Hour Glass", tier = "A", icon = "沙", desc = "回到上一个房间并恢复此前状态。" },
    { id = 58, cat = "active", name = "影之书", en = "Book of Shadows", tier = "A", icon = "书", desc = "短时间无敌，适合 Boss 与献祭场景。" },
    { id = 292, cat = "active", name = "撒旦圣经", en = "Satanic Bible", tier = "A", icon = "书", desc = "提供黑心，并改变 Boss 房奖励机制。" },
    { id = 347, cat = "active", name = "二倍视野", en = "Diplopia", tier = "A", icon = "×2", desc = "复制当前房间内的道具与掉落物。" },
    { id = 360, cat = "familiar", name = "梦魇宝宝", en = "Incubus", tier = "S", icon = "魔", desc = "复制角色的泪弹攻击，是高强度输出跟班。", hot = 1 },
    { id = 698, cat = "familiar", name = "扭曲的双子", en = "Twisted Pair", tier = "S", icon = "双", desc = "两个恶魔跟班同时复制射击，提供可观伤害。", hot = 1 },
    { id = 417, cat = "familiar", name = "魅魔", en = "Succubus", tier = "S", icon = "魅", desc = "伤害光环会攻击敌人并增强范围内的角色伤害。", hot = 1 },
    { id = 387, cat = "familiar", name = "撒拉弗", en = "Seraphim", tier = "A", icon = "天", desc = "发射高伤害圣心泪弹。" },
    { id = 268, cat = "familiar", name = "腐烂宝宝", en = "Rotten Baby", tier = "A", icon = "腐", desc = "发射攻击苍蝇，输出稳定。" },
    { id = 275, cat = "familiar", name = "小硫磺火", en = "Lil Brimstone", tier = "A", icon = "硫", desc = "蓄力发射短程硫磺火激光。" },
    { id = 265, cat = "familiar", name = "干瘪宝宝", en = "Dry Baby", tier = "A", icon = "干", desc = "格挡弹幕，并有概率触发全房伤害。" },
    { id = 270, cat = "familiar", name = "水蛭", en = "Leech", tier = "A", icon = "蛭", desc = "主动追咬敌人，击杀时可回复红心。" },
    { id = 247, cat = "familiar", name = "好朋友一辈子！", en = "BFFS!", tier = "A", icon = "友", desc = "强化大多数跟班的体积与伤害。" },
    { id = 721, cat = "fun", name = "TMTRAINER", en = "TMTRAINER", tier = "S", icon = "错", desc = "后续道具变成随机故障效果，极度混沌。", hot = 1 },
    { id = 700, cat = "fun", name = "回声室", en = "Echo Chamber", tier = "S", icon = "回", desc = "使用消耗品时重复此前效果，容易形成夸张连锁。", hot = 1 },
    { id = 625, cat = "fun", name = "超级蘑菇", en = "Mega Mush", tier = "S", icon = "巨", desc = "短时间变成巨人，碾压敌人与障碍。", hot = 1 },
    { id = 330, cat = "fun", name = "豆浆", en = "Soy Milk", tier = "A", icon = "奶", desc = "伤害大幅下降但射速暴涨，联动潜力很高。" },
    { id = 561, cat = "fun", name = "杏仁奶", en = "Almond Milk", tier = "A", icon = "杏", desc = "超高射速并让泪弹获得随机弹道。" },
    { id = 494, cat = "fun", name = "雅各布天梯", en = "Jacob's Ladder", tier = "A", icon = "电", desc = "泪弹命中后释放连锁电击。" },
    { id = 418, cat = "fun", name = "水果蛋糕", en = "Fruit Cake", tier = "A", icon = "糕", desc = "每颗泪弹获得随机特殊效果。" },
    { id = 529, cat = "fun", name = "噗！", en = "Pop!", tier = "A", icon = "泡", desc = "泪弹彼此碰撞并持续存在，形成弹幕。" },
    { id = 570, cat = "fun", name = "橡皮泥饼干", en = "Playdough Cookie", tier = "A", icon = "彩", desc = "泪弹随机获得不同元素效果。" },
    { id = 233, cat = "fun", name = "小小星球", en = "Tiny Planet", tier = "A", icon = "星", desc = "泪弹围绕角色旋转，改变射击逻辑。" },
  },
  commands = {
    { cat = "debug", name = "无敌模式", en = "Debug Flag 3", tier = "S", icon = "∞", desc = "角色不再受到伤害；再次执行可关闭。", cmd = "debug 3" },
    { cat = "debug", name = "超高伤害", en = "Debug Flag 4", tier = "S", icon = "爆", desc = "赋予极高伤害，快速测试房间与 Boss。", cmd = "debug 4" },
    { cat = "debug", name = "无限充能", en = "Debug Flag 8", tier = "S", icon = "充", desc = "主动道具获得无限充能；再次执行可关闭。", cmd = "debug 8" },
    { cat = "debug", name = "超高幸运", en = "Debug Flag 9", tier = "A", icon = "运", desc = "把幸运提高到很高水平，便于测试触发类效果。", cmd = "debug 9" },
    { cat = "debug", name = "快速击杀", en = "Debug Flag 10", tier = "A", icon = "杀", desc = "敌人会快速死亡；再次执行可关闭。", cmd = "debug 10" },
    { cat = "debug", name = "显示碰撞箱", en = "Debug Flag 6", tier = "A", icon = "框", desc = "显示实体碰撞范围，用于观察躲弹判定。", cmd = "debug 6" },
    { cat = "debug", name = "显示伤害值", en = "Debug Flag 7", tier = "A", icon = "数", desc = "显示伤害数值与相关调试信息。", cmd = "debug 7" },
    { cat = "debug", name = "显示房间信息", en = "Debug Flag 5", tier = "A", icon = "房", desc = "显示当前房间的调试信息。", cmd = "debug 5" },
    { cat = "supply", name = "99 枚硬币", en = "A Dollar", tier = "S", icon = "$", desc = "通过“一美元”一次性补足大量硬币；资源增加由游戏 ItemConfig 声明，不能通过移除道具回退。", cmd = "giveitem c18" },
    { cat = "supply", name = "99 把钥匙", en = "Skeleton Key", tier = "S", icon = "钥", desc = "通过“骷髅钥匙”一次性补足大量钥匙；资源增加由游戏 ItemConfig 声明，不能通过移除道具回退。", cmd = "giveitem c17" },
    { cat = "supply", name = "99 枚炸弹", en = "Pyro", tier = "S", icon = "弹", desc = "通过“烟火盛宴”一次性补足大量炸弹；资源增加由游戏 ItemConfig 声明，不能通过移除道具回退。", cmd = "giveitem c190" },
    { cat = "supply", name = "生成魂心", en = "Soul Heart", tier = "A", icon = "魂", desc = "在角色附近生成一颗魂心。", cmd = "spawn 5.10.3" },
    { cat = "supply", name = "生成永恒之心", en = "Eternal Heart", tier = "A", icon = "白", desc = "在角色附近生成一颗永恒之心。", cmd = "spawn 5.10.4" },
    { cat = "supply", name = "生成金箱", en = "Golden Chest", tier = "A", icon = "箱", desc = "在角色附近生成一个金箱。", cmd = "spawn 5.50.1" },
    { cat = "supply", name = "生成随机道具", en = "Random Pedestal", tier = "A", icon = "?", desc = "在角色附近生成一个随机道具底座。", cmd = "spawn 5.100.0" },
    { cat = "supply", name = "清空当前房间敌人", en = "Kill Room", tier = "A", icon = "清", desc = "立即击杀当前房间中的敌人。", cmd = "kill" },
    -- Normal/Hard mode floor whitelist. Do not generate arbitrary suffixes:
    -- the native stage command may crash on nonexistent stage/type pairs.
    { cat = "stage", name = "地下室 I", en = "Basement I", tier = "A", icon = "1", desc = "跳转到地下室第一层。", cmd = "stage 1" },
    { cat = "stage", name = "地窖 I", en = "Cellar I", tier = "A", icon = "1a", desc = "跳转到地窖第一层。", cmd = "stage 1a" },
    { cat = "stage", name = "燃烧地下室 I", en = "Burning Basement I", tier = "A", icon = "1b", desc = "跳转到燃烧地下室第一层。", cmd = "stage 1b" },
    { cat = "stage", name = "下水道 I", en = "Downpour I", tier = "S", icon = "1c", desc = "跳转到忏悔支线下水道第一层。", cmd = "stage 1c" },
    { cat = "stage", name = "污水井 I", en = "Dross I", tier = "S", icon = "1d", desc = "跳转到忏悔支线污水井第一层。", cmd = "stage 1d" },
    { cat = "stage", name = "地下室 II", en = "Basement II", tier = "A", icon = "2", desc = "跳转到地下室第二层。", cmd = "stage 2" },
    { cat = "stage", name = "地窖 II", en = "Cellar II", tier = "A", icon = "2a", desc = "跳转到地窖第二层。", cmd = "stage 2a" },
    { cat = "stage", name = "燃烧地下室 II", en = "Burning Basement II", tier = "A", icon = "2b", desc = "跳转到燃烧地下室第二层。", cmd = "stage 2b" },
    { cat = "stage", name = "下水道 II", en = "Downpour II", tier = "S", icon = "2c", desc = "跳转到忏悔支线下水道第二层。", cmd = "stage 2c" },
    { cat = "stage", name = "污水井 II", en = "Dross II", tier = "S", icon = "2d", desc = "跳转到忏悔支线污水井第二层。", cmd = "stage 2d" },
    { cat = "stage", name = "洞穴 I", en = "Caves I", tier = "A", icon = "3", desc = "跳转到洞穴第一层。", cmd = "stage 3" },
    { cat = "stage", name = "墓穴 I", en = "Catacombs I", tier = "A", icon = "3a", desc = "跳转到墓穴第一层。", cmd = "stage 3a" },
    { cat = "stage", name = "淹水洞穴 I", en = "Flooded Caves I", tier = "A", icon = "3b", desc = "跳转到淹水洞穴第一层。", cmd = "stage 3b" },
    { cat = "stage", name = "矿坑 I", en = "Mines I", tier = "S", icon = "3c", desc = "跳转到忏悔支线矿坑第一层。", cmd = "stage 3c" },
    { cat = "stage", name = "灰坑 I", en = "Ashpit I", tier = "S", icon = "3d", desc = "跳转到忏悔支线灰坑第一层。", cmd = "stage 3d" },
    { cat = "stage", name = "洞穴 II", en = "Caves II", tier = "A", icon = "4", desc = "跳转到洞穴第二层。", cmd = "stage 4" },
    { cat = "stage", name = "墓穴 II", en = "Catacombs II", tier = "A", icon = "4a", desc = "跳转到墓穴第二层。", cmd = "stage 4a" },
    { cat = "stage", name = "淹水洞穴 II", en = "Flooded Caves II", tier = "A", icon = "4b", desc = "跳转到淹水洞穴第二层。", cmd = "stage 4b" },
    { cat = "stage", name = "矿坑 II", en = "Mines II", tier = "S", icon = "4c", desc = "跳转到忏悔支线矿坑第二层。", cmd = "stage 4c" },
    { cat = "stage", name = "灰坑 II", en = "Ashpit II", tier = "S", icon = "4d", desc = "跳转到忏悔支线灰坑第二层。", cmd = "stage 4d" },
    { cat = "stage", name = "深牢 I", en = "Depths I", tier = "A", icon = "5", desc = "跳转到深牢第一层。", cmd = "stage 5" },
    { cat = "stage", name = "坟场 I", en = "Necropolis I", tier = "A", icon = "5a", desc = "跳转到坟场第一层。", cmd = "stage 5a" },
    { cat = "stage", name = "阴湿深牢 I", en = "Dank Depths I", tier = "A", icon = "5b", desc = "跳转到阴湿深牢第一层。", cmd = "stage 5b" },
    { cat = "stage", name = "陵墓 I", en = "Mausoleum I", tier = "S", icon = "5c", desc = "跳转到忏悔支线陵墓第一层。", cmd = "stage 5c" },
    { cat = "stage", name = "炼狱 I", en = "Gehenna I", tier = "S", icon = "5d", desc = "跳转到忏悔支线炼狱第一层。", cmd = "stage 5d" },
    { cat = "stage", name = "深牢 II", en = "Depths II", tier = "A", icon = "6", desc = "跳转到妈妈所在的深牢第二层。", cmd = "stage 6" },
    { cat = "stage", name = "坟场 II", en = "Necropolis II", tier = "A", icon = "6a", desc = "跳转到坟场第二层。", cmd = "stage 6a" },
    { cat = "stage", name = "阴湿深牢 II", en = "Dank Depths II", tier = "A", icon = "6b", desc = "跳转到阴湿深牢第二层。", cmd = "stage 6b" },
    { cat = "stage", name = "陵墓 II", en = "Mausoleum II", tier = "S", icon = "6c", desc = "跳转到忏悔支线陵墓第二层。", cmd = "stage 6c" },
    { cat = "stage", name = "炼狱 II", en = "Gehenna II", tier = "S", icon = "6d", desc = "跳转到忏悔支线炼狱第二层。", cmd = "stage 6d" },
    { cat = "stage", name = "子宫 I", en = "Womb I", tier = "A", icon = "7", desc = "跳转到子宫第一层。", cmd = "stage 7" },
    { cat = "stage", name = "胎衣 I", en = "Utero I", tier = "A", icon = "7a", desc = "跳转到胎衣第一层。", cmd = "stage 7a" },
    { cat = "stage", name = "瘢痕子宫 I", en = "Scarred Womb I", tier = "A", icon = "7b", desc = "跳转到瘢痕子宫第一层。", cmd = "stage 7b" },
    { cat = "stage", name = "尸宫 I", en = "Corpse I", tier = "S", icon = "7c", desc = "跳转到忏悔支线尸宫第一层。", cmd = "stage 7c" },
    { cat = "stage", name = "子宫 II", en = "Womb II", tier = "A", icon = "8", desc = "跳转到子宫第二层。", cmd = "stage 8" },
    { cat = "stage", name = "胎衣 II", en = "Utero II", tier = "A", icon = "8a", desc = "跳转到胎衣第二层。", cmd = "stage 8a" },
    { cat = "stage", name = "瘢痕子宫 II", en = "Scarred Womb II", tier = "A", icon = "8b", desc = "跳转到瘢痕子宫第二层。", cmd = "stage 8b" },
    { cat = "stage", name = "尸宫 II", en = "Corpse II", tier = "S", icon = "8c", desc = "跳转到忏悔支线尸宫第二层。", cmd = "stage 8c" },
    { cat = "stage", name = "蓝子宫", en = "Blue Womb", tier = "S", icon = "9", desc = "跳转到 Hush 所在的蓝子宫。", cmd = "stage 9" },
    { cat = "stage", name = "阴间", en = "Sheol", tier = "A", icon = "10", desc = "跳转到阴间。", cmd = "stage 10" },
    { cat = "stage", name = "教堂", en = "Cathedral", tier = "A", icon = "10a", desc = "跳转到教堂。", cmd = "stage 10a" },
    { cat = "stage", name = "暗室", en = "Dark Room", tier = "A", icon = "11", desc = "跳转到暗室。", cmd = "stage 11" },
    { cat = "stage", name = "宝箱层", en = "The Chest", tier = "A", icon = "11a", desc = "跳转到宝箱层。", cmd = "stage 11a" },
    { cat = "stage", name = "虚空", en = "The Void", tier = "S", icon = "12", desc = "跳转到精神错乱所在的虚空。", cmd = "stage 12" },
    { cat = "stage", name = "家", en = "Home", tier = "S", icon = "13", desc = "跳转到忏悔最终路线的家。", cmd = "stage 13" },
    -- Greed and Greedier use a separate, documented stage 1-7 progression.
    -- Do not add suffixes or stage 8+: those are not part of the public Greed route.
    { cat = "stage", name = "地下室（贪婪）", stageMode = "greed", en = "Basement (Greed)", tier = "A", icon = "G1", desc = "跳转到贪婪模式的地下室。", cmd = "stage 1" },
    { cat = "stage", name = "洞穴（贪婪）", stageMode = "greed", en = "Caves (Greed)", tier = "A", icon = "G2", desc = "跳转到贪婪模式的洞穴。", cmd = "stage 2" },
    { cat = "stage", name = "深牢（贪婪）", stageMode = "greed", en = "Depths (Greed)", tier = "A", icon = "G3", desc = "跳转到贪婪模式的深牢。", cmd = "stage 3" },
    { cat = "stage", name = "子宫（贪婪）", stageMode = "greed", en = "Womb (Greed)", tier = "A", icon = "G4", desc = "跳转到贪婪模式的子宫。", cmd = "stage 4" },
    { cat = "stage", name = "阴间（贪婪）", stageMode = "greed", en = "Sheol (Greed)", tier = "A", icon = "G5", desc = "跳转到贪婪模式的阴间。", cmd = "stage 5" },
    { cat = "stage", name = "商店（贪婪）", stageMode = "greed", en = "The Shop (Greed)", tier = "S", icon = "G6", desc = "跳转到贪婪模式的商店层。", cmd = "stage 6" },
    { cat = "stage", name = "究极贪婪", stageMode = "greed", en = "Ultra Greed", tier = "S", icon = "G7", desc = "跳转到究极贪婪所在楼层。", cmd = "stage 7" },
  },
}
