return {
  categories = {
    { id = "run_control", group = "Console", icon = "RUN", name = "Run Control", desc = "Run debug toggles, refresh actions, rewinds, restarts, and floor resets.", shortDesc = "Debug, refresh, and run control", eyebrow = "RUN CONTROL" },
    { id = "command_reference", group = "Console", icon = "REF", name = "Command Reference", desc = "Official syntax reference. Press C to complete parameter commands; disabled entries are reference-only.", shortDesc = "Official syntax and safety status", eyebrow = "COMMAND REFERENCE" },
    { id = "custom_commands", group = "Console", icon = "CUS", name = "Custom Commands", desc = "Advanced raw-command passthrough with optional names, search, favorites, editing, and deletion; use at your own risk.", shortDesc = "Advanced raw-command passthrough", eyebrow = "CUSTOM COMMANDS" },
  },
  commands = {
    { commandId = "rewind", cat = "run_control", name = "Rewind Room", en = "Rewind", icon = "RW", tier = "S", desc = "Returns to the previous room state.", cmd = "rewind" },
    { commandId = "restart", cat = "run_control", name = "Restart Run", en = "Restart", icon = "R", tier = "S", desc = "Restarts with the current character.", cmd = "restart" },
    { commandId = "reseed", cat = "run_control", name = "Reseed Floor", en = "Reseed Floor", icon = "SEED", tier = "S", desc = "Regenerates the current floor.", cmd = "reseed" },
    { commandId = "debug", cat = "run_control", name = "Held Collectibles", en = "Debug Flag 12", icon = "12", tier = "A", desc = "Shows held collectibles and temporary effects. Run again to hide.", cmd = "debug 12" },
    { commandId = "debug", cat = "run_control", name = "Grid Collision Points", en = "Debug Flag 13", icon = "13", tier = "A", desc = "Shows entity grid-collision points. Run again to hide.", cmd = "debug 13" },
    { commandId = "costumetest", cat = "run_control", name = "Random Costumes", en = "Costume Test", icon = "CST", tier = "A", desc = "Adds random costumes without granting their associated items.", cmd = "costumetest" },
    { commandId = "clearseeds", cat = "run_control", name = "Clear Special Seeds", en = "Clear Seeds", icon = "CLR", tier = "A", desc = "Removes special-seed effects from the current run.", cmd = "clearseeds" },
    { commandId = "restock", cat = "run_control", name = "Restock Room", en = "Restock", icon = "RST", tier = "A", desc = "Restocks shop or item pedestals in the current room.", cmd = "restock" },
    { commandId = "reloadwisps", cat = "run_control", name = "Reload Wisps", en = "Reload Wisps", icon = "WSP", tier = "A", desc = "Reloads Book of Virtues wisps and Abyss locusts.", cmd = "reloadwisps" },
    { commandId = "spawn", cat = "command_reference", name = "Spawn Entity", en = "spawn", icon = "SPN", tier = "A", desc = "Syntax reference for type.variant.subtype.champion.", catalogAction = "manual" },
    { commandId = "goto", cat = "command_reference", name = "Go To Room", en = "goto", icon = "ROOM", tier = "S", desc = "Jumps immediately by room category, ID, or dimension.", catalogAction = "manual" },
    { commandId = "stage", cat = "command_reference", name = "Go To Stage", en = "stage", icon = "STG", tier = "S", desc = "Stage 1-13 plus optional a-d; only stage combinations available in the current mode are allowed.", catalogAction = "manual" },
    { commandId = "gridspawn", cat = "command_reference", name = "Spawn Grid Entity", en = "gridspawn", icon = "GRID", tier = "A", desc = "Spawns a grid entity in the current room.", catalogAction = "manual" },
    { commandId = "debug", cat = "command_reference", name = "Debug Flag", en = "debug", icon = "DBG", tier = "A", desc = "Toggles a specified debug flag.", catalogAction = "manual" },
    { commandId = "giveitem", cat = "command_reference", name = "Give Item", en = "giveitem / g", icon = "GIV", tier = "A", desc = "Gives a collectible, trinket, pill, or card.", catalogAction = "manual" },
    { commandId = "remove", cat = "command_reference", name = "Remove Item", en = "remove / r", icon = "REM", tier = "A", desc = "Removes a specified collectible or trinket.", catalogAction = "manual" },
    { commandId = "restart", cat = "command_reference", name = "Restart as Character", en = "restart", icon = "CHR", tier = "S", desc = "Character ID must be in the official 0-40 range.", catalogAction = "manual" },
    { commandId = "seed", cat = "command_reference", name = "Start Seed", en = "seed", icon = "SEED", tier = "S", desc = "Starts a run with an uppercase XXXX XXXX seed.", catalogAction = "manual" },
    { commandId = "challenge", cat = "command_reference", name = "Start Challenge", en = "challenge", icon = "CHL", tier = "S", desc = "Only challenge IDs available in the current game version are allowed.", catalogAction = "manual" },
    { commandId = "combo", cat = "command_reference", name = "Give Combo", en = "combo", icon = "CMB", tier = "A", desc = "Gives a count of random items from an item pool.", catalogAction = "manual" },
    { commandId = "playsfx", cat = "command_reference", name = "Play Sound", en = "playsfx", icon = "SFX", tier = "A", desc = "Plays the specified sound-effect ID.", catalogAction = "manual" },
    { commandId = "curse", cat = "command_reference", name = "Set Curse", en = "curse", icon = "CRS", tier = "A", desc = "Curse bitmask is restricted to 0-255.", catalogAction = "manual" },
    { commandId = "metro", cat = "command_reference", name = "Metronome Test", en = "metro", icon = "MET", tier = "A", desc = "Developer metronome command syntax reference.", catalogAction = "manual" },
    { commandId = "delirious", cat = "command_reference", name = "Delirious Form", en = "delirious", icon = "DEL", tier = "A", desc = "Sets the boss form used by Delirious.", catalogAction = "manual" },
    { commandId = "listcollectibles", cat = "command_reference", name = "List Collectibles", en = "listcollectibles", icon = "OUT", tier = "D", desc = "Output is visible only in the native console; this UI has no output page.", catalogAction = "disabled" },
    { commandId = "copy", cat = "command_reference", name = "Copy Console Output", en = "copy", icon = "OUT", tier = "D", desc = "Requires the native console and system clipboard; disabled here.", catalogAction = "disabled" },
    { commandId = "clear", cat = "command_reference", name = "Clear Console Output", en = "clear", icon = "OUT", tier = "D", desc = "Only affects native-console output; disabled here.", catalogAction = "disabled" },
    { commandId = "luamem", cat = "command_reference", name = "Lua Memory Output", en = "luamem", icon = "OUT", tier = "D", desc = "Prints diagnostics only to the native console; disabled here.", catalogAction = "disabled" },
    { commandId = "testbosspool", cat = "command_reference", name = "Boss Pool Output", en = "testbosspool", icon = "OUT", tier = "D", desc = "Prints test output only to the native console; disabled here.", catalogAction = "disabled" },
    { commandId = "lua", cat = "command_reference", name = "Execute Lua", en = "lua / l", icon = "NO", tier = "D", desc = "Can execute arbitrary code and is disabled in the Workshop build.", catalogAction = "disabled" },
    { commandId = "luarun", cat = "command_reference", name = "Run Lua File", en = "luarun", icon = "NO", tier = "D", desc = "Can execute an external Lua file and is disabled here.", catalogAction = "disabled" },
    { commandId = "luamod", cat = "command_reference", name = "Reload Mod Lua", en = "luamod", icon = "NO", tier = "D", desc = "Reloads Mod code and state and is disabled here.", catalogAction = "disabled" },
    { commandId = "achievement", cat = "command_reference", name = "Change Achievement", en = "achievement", icon = "NO", tier = "D", desc = "May change persistent progress and is disabled here.", catalogAction = "disabled" },
    { commandId = "prof", cat = "command_reference", name = "Profiler", en = "prof", icon = "NO", tier = "D", desc = "Internal process-level developer command; disabled here.", catalogAction = "disabled" },
    { commandId = "fullrestart", cat = "command_reference", name = "Full Restart", en = "fullrestart", icon = "NO", tier = "D", desc = "Restarts the game process and is disabled here.", catalogAction = "disabled" },
    { commandId = "quit", cat = "command_reference", name = "Quit Game", en = "quit", icon = "NO", tier = "D", desc = "Exits the game process and is disabled here.", catalogAction = "disabled" },
    { commandId = "macro", cat = "command_reference", name = "Run Macro", en = "macro / m", icon = "NO", tier = "D", desc = "Can indirectly execute multiple unknown commands and is disabled here.", catalogAction = "disabled" },
    { commandId = "repeat", cat = "command_reference", name = "Repeat Command", en = "repeat", icon = "NO", tier = "D", desc = "Target and count cannot be constrained reliably, so it is disabled here.", catalogAction = "disabled" },
  },
}
