-- Independent English catalog for Console UI v2.5.2-en.2.
return {
  categories = {
    { id = "featured", group = "Items", icon = "*", name = "Featured", desc = "Your most recently favorited entries appear first.", shortDesc = "Recent favorite entries.", eyebrow = "MY FAVORITES" },
    { id = "all_items", group = "Items", icon = "ALL", name = "Collectibles", desc = "All collectibles in the current game version.", shortDesc = "All official collectibles.", eyebrow = "COLLECTIBLES" },
    { id = "trinkets", group = "Items", icon = "TR", name = "Trinkets", desc = "Official base trinkets. Granted trinkets can also be removed.", shortDesc = "Give and remove trinkets.", eyebrow = "TRINKETS" },
    { id = "cards", group = "Items", icon = "CRD", name = "Cards & Runes", desc = "Official cards, runes, reversed cards, and soul stones. Grants are single-use commands.", shortDesc = "Give cards and runes once.", eyebrow = "CARDS & RUNES" },
    { id = "pills", group = "Items", icon = "PIL", name = "Pill Effects", desc = "Official base pill effects. Grants are single-use commands.", shortDesc = "Give pill effects once.", eyebrow = "PILL EFFECTS" },
    { id = "damage", group = "Items", icon = "DMG", name = "Damage", desc = "Damage upgrades, tear replacements, and powerful build-defining synergies.", shortDesc = "Damage and tear upgrades.", eyebrow = "DAMAGE & TEARS" },
    { id = "defense", group = "Items", icon = "DEF", name = "Defense", desc = "Shields, damage reduction, and immunity.", shortDesc = "Shields and survival items.", eyebrow = "SURVIVAL" },
    { id = "economy", group = "Items", icon = "$", name = "Economy", desc = "Shop value, pickup generation, and long-term resource growth.", shortDesc = "Shops, pickups, and resources.", eyebrow = "ECONOMY" },
    { id = "explore", group = "Items", icon = "MAP", name = "Exploration", desc = "Map information, secret-room access, and room-navigation tools.", shortDesc = "Maps, secrets, and movement.", eyebrow = "NAVIGATION" },
    { id = "active", group = "Items", icon = "ACT", name = "Active Items", desc = "Rerolls, rewinds, restarts, and other run-changing active items.", shortDesc = "Run-changing active items.", eyebrow = "ACTIVE ITEMS" },
    { id = "familiar", group = "Items", icon = "FAM", name = "Familiars", desc = "Familiars for damage, projectile blocking, and sustain.", shortDesc = "Damage and support familiars.", eyebrow = "FAMILIARS" },
    { id = "fun", group = "Items", icon = "FUN", name = "Chaos Lab", desc = "Experimental picks for testing builds and creating wild synergies.", shortDesc = "Experimental build tools.", eyebrow = "CHAOS LAB" },
    { id = "debug", group = "Console", icon = "DBG", name = "Debug Flags", desc = "Invincibility, extreme damage, unlimited charge, and diagnostic overlays. Run the same debug command again to turn it off.", shortDesc = "Toggle debug flags.", eyebrow = "DEBUG FLAGS" },
    { id = "supply", group = "Console", icon = "+", name = "Supplies", desc = "Spawn pickups, restore resources, and control the current room.", shortDesc = "Spawn pickups and resources.", eyebrow = "SUPPLY DROP" },
    { id = "stage", group = "Console", icon = "STG", name = "Stage Warp", desc = "Shows the safe route for the current mode: 45 Normal/Hard destinations or 7 Greed destinations.", shortDesc = "Warp along the safe route.", eyebrow = "STAGE WARP" },
  },
  items = {
    { id = 182, cat = "damage", name = "Sacred Heart", en = "Sacred Heart", tier = "S", icon = "SH", desc = "A large damage multiplier, homing tears, and extra health make this one of the most reliable top-tier damage items.", hot = 1 },
    { id = 331, cat = "damage", name = "Godhead", en = "Godhead", tier = "S", icon = "GH", desc = "Homing tears gain a damaging aura that clears rooms and melts bosses.", hot = 1 },
    { id = 118, cat = "damage", name = "Brimstone", en = "Brimstone", tier = "S", icon = "BR", desc = "Replaces tears with a charged blood laser that pierces across the room.", hot = 1 },
    { id = 114, cat = "damage", name = "Mom's Knife", en = "Mom's Knife", tier = "S", icon = "MK", desc = "Replaces tears with a charged knife that deals exceptional damage at any range.", hot = 1 },
    { id = 678, cat = "damage", name = "C Section", en = "C Section", tier = "S", icon = "CS", desc = "Fires homing fetus projectiles with excellent base power and broad synergy support.", hot = 1 },
    { id = 395, cat = "damage", name = "Tech X", en = "Tech X", tier = "S", icon = "TX", desc = "Fires charged laser rings with piercing, wide coverage, and obstacle penetration.", hot = 1 },
    { id = 531, cat = "damage", name = "Haemolacria", en = "Haemolacria", tier = "S", icon = "HM", desc = "Arcing tears burst into smaller projectiles on impact for huge area damage.", hot = 1 },
    { id = 169, cat = "damage", name = "Polyphemus", en = "Polyphemus", tier = "S", icon = "POL", desc = "Massively increases damage at the cost of fire rate, creating devastating individual shots.", hot = 1 },
    { id = 562, cat = "damage", name = "Rock Bottom", en = "Rock Bottom", tier = "S", icon = "RB", desc = "Prevents displayed stats from dropping below their highest values, enabling extreme scaling.", hot = 1 },
    { id = 691, cat = "damage", name = "Sacred Orb", en = "Sacred Orb", tier = "S", icon = "SO", desc = "Improves future item quality and reduces the chance of low-quality items appearing.", hot = 1 },
    { id = 689, cat = "damage", name = "Glitched Crown", en = "Glitched Crown", tier = "S", icon = "GC", desc = "Cycles each item pedestal through several choices, greatly increasing access to powerful items.", hot = 1 },
    { id = 12, cat = "damage", name = "Magic Mushroom", en = "Magic Mushroom", tier = "A", icon = "MM", desc = "A broad all-stats upgrade with a strong damage multiplier." },
    { id = 4, cat = "damage", name = "Cricket's Head", en = "Cricket's Head", tier = "A", icon = "CH", desc = "A simple, powerful damage increase with a multiplicative bonus." },
    { id = 415, cat = "damage", name = "Crown of Light", en = "Crown of Light", tier = "A", icon = "CL", desc = "Greatly increases damage and range while Isaac has full red-heart health." },
    { id = 245, cat = "damage", name = "20/20", en = "20/20", tier = "A", icon = "20", desc = "Fires two tears at once, providing a dependable multishot upgrade." },
    { id = 313, cat = "defense", name = "Holy Mantle", en = "Holy Mantle", tier = "S", icon = "HM", desc = "Blocks one hit in every room, providing exceptional consistency and safety.", hot = 1 },
    { id = 108, cat = "defense", name = "The Wafer", en = "The Wafer", tier = "S", icon = "WF", desc = "Reduces most damage to half a heart, dramatically improving late-game survival.", hot = 1 },
    { id = 581, cat = "defense", name = "Psy Fly", en = "Psy Fly", tier = "S", icon = "PSY", desc = "Actively intercepts enemy projectiles and excels against bullet-heavy bosses.", hot = 1 },
    { id = 223, cat = "defense", name = "Pyromaniac", en = "Pyromaniac", tier = "S", icon = "PYR", desc = "Grants explosion immunity and lets explosions heal red hearts.", hot = 1 },
    { id = 375, cat = "defense", name = "Host Hat", en = "Host Hat", tier = "A", icon = "HH", desc = "Grants explosion immunity and a chance to block enemy projectiles." },
    { id = 210, cat = "defense", name = "Gnawed Leaf", en = "Gnawed Leaf", tier = "A", icon = "GL", desc = "Standing still long enough grants invincibility, especially useful with autonomous familiars." },
    { id = 81, cat = "defense", name = "Dead Cat", en = "Dead Cat", tier = "A", icon = "9L", desc = "Grants nine lives but sets red-heart containers to one." },
    { id = 232, cat = "defense", name = "Stop Watch", en = "Stop Watch", tier = "A", icon = "SW", desc = "Permanently slows most enemies and hostile projectiles." },
    { id = 242, cat = "defense", name = "Infamy", en = "Infamy", tier = "A", icon = "INF", desc = "Has a chance to block damage coming from the direction Isaac is facing." },
    { id = 64, cat = "economy", name = "Steam Sale", en = "Steam Sale", tier = "S", icon = "$", desc = "Halves shop prices; the earlier it appears, the more value it provides.", hot = 1 },
    { id = 203, cat = "economy", name = "Humbling Bundle", en = "Humbling Bundle", tier = "S", icon = "HB", desc = "Makes most basic pickups appear in pairs, greatly increasing resources.", hot = 1 },
    { id = 241, cat = "economy", name = "Contract From Below", en = "Contract From Below", tier = "S", icon = "CFB", desc = "Greatly increases the number of pickups awarded after clearing rooms.", hot = 1 },
    { id = 716, cat = "economy", name = "Keeper's Sack", en = "Keeper's Sack", tier = "S", icon = "KS", desc = "Spending money in shops grants lasting stat upgrades.", hot = 1 },
    { id = 416, cat = "economy", name = "Deep Pockets", en = "Deep Pockets", tier = "A", icon = "DP", desc = "Raises the coin cap to 999 and improves rewards from otherwise empty rooms." },
    { id = 424, cat = "economy", name = "Sack Head", en = "Sack Head", tier = "A", icon = "SAC", desc = "Gives pickups a chance to be replaced by sacks containing multiple resources." },
    { id = 429, cat = "economy", name = "Head of the Keeper", en = "Head of the Keeper", tier = "A", icon = "HOK", desc = "Tears have a chance to drop coins when they hit enemies." },
    { id = 109, cat = "economy", name = "Money = Power", en = "Money = Power", tier = "A", icon = "$", desc = "Damage increases with the number of coins currently held." },
    { id = 249, cat = "economy", name = "There's Options", en = "There's Options", tier = "A", icon = "?", desc = "Boss rewards offer two items to choose from." },
    { id = 414, cat = "economy", name = "More Options", en = "More Options", tier = "A", icon = "+", desc = "Treasure Rooms offer two items to choose from." },
    { id = 21, cat = "explore", name = "The Compass", en = "The Compass", tier = "A", icon = "CMP", desc = "Reveals special-room icons on the map.", hot = 1 },
    { id = 54, cat = "explore", name = "Treasure Map", en = "Treasure Map", tier = "A", icon = "MAP", desc = "Reveals the current floor's room layout.", hot = 1 },
    { id = 246, cat = "explore", name = "Blue Map", en = "Blue Map", tier = "A", icon = "BLU", desc = "Reveals Secret Rooms and Super Secret Rooms on the map.", hot = 1 },
    { id = 76, cat = "explore", name = "X-Ray Vision", en = "X-Ray Vision", tier = "A", icon = "X", desc = "Automatically opens most Secret Room entrances.", hot = 1 },
    { id = 580, cat = "explore", name = "Red Key", en = "Red Key", tier = "S", icon = "RED", desc = "Opens Red Rooms from valid walls, revealing hidden areas of the floor.", hot = 1 },
    { id = 419, cat = "explore", name = "Teleport 2.0", en = "Teleport 2.0", tier = "A", icon = "T20", desc = "Teleports through unvisited rooms in progression order and can reach special rooms." },
    { id = 91, cat = "explore", name = "Spelunker Hat", en = "Spelunker Hat", tier = "A", icon = "HAT", desc = "Shows adjacent room types and helps locate Secret Rooms." },
    { id = 175, cat = "explore", name = "Dad's Key", en = "Dad's Key", tier = "A", icon = "KEY", desc = "Opens doors in the current room, including several special doors." },
    { id = 84, cat = "explore", name = "We Need to Go Deeper!", en = "We Need to Go Deeper!", tier = "A", icon = "DIG", desc = "Creates a trapdoor to the next floor." },
    { id = 105, cat = "active", name = "The D6", en = "The D6", tier = "S", icon = "D6", desc = "Rerolls item pedestals in the room and is one of the most versatile active items.", hot = 1 },
    { id = 489, cat = "active", name = "D Infinity", en = "D Infinity", tier = "S", icon = "DI", desc = "Switches between multiple dice effects for exceptional flexibility.", hot = 1 },
    { id = 723, cat = "active", name = "Spindown Dice", en = "Spindown Dice", tier = "S", icon = "SD", desc = "Rerolls items to lower IDs, allowing consistent access to specific powerful items.", hot = 1 },
    { id = 636, cat = "active", name = "R Key", en = "R Key", tier = "S", icon = "R", desc = "Restarts the run while keeping the current build, enabling extended routes.", hot = 1 },
    { id = 628, cat = "active", name = "Death Certificate", en = "Death Certificate", tier = "S", icon = "DC", desc = "Enters a special area containing every item and lets Isaac choose one.", hot = 1 },
    { id = 622, cat = "active", name = "Genesis", en = "Genesis", tier = "S", icon = "GEN", desc = "Rebuilds the current inventory through a series of choices in a special area.", hot = 1 },
    { id = 477, cat = "active", name = "Void", en = "Void", tier = "A", icon = "V", desc = "Consumes items, absorbing active effects and converting passive items into stats." },
    { id = 476, cat = "active", name = "The D1", en = "The D1", tier = "A", icon = "D1", desc = "Duplicates a random pickup in the current room." },
    { id = 422, cat = "active", name = "Glowing Hour Glass", en = "Glowing Hour Glass", tier = "A", icon = "GHG", desc = "Returns to the previous room and restores the earlier state." },
    { id = 58, cat = "active", name = "Book of Shadows", en = "Book of Shadows", tier = "A", icon = "BOS", desc = "Grants temporary invincibility for bosses, sacrifice rooms, and other hazards." },
    { id = 292, cat = "active", name = "Satanic Bible", en = "Satanic Bible", tier = "A", icon = "SB", desc = "Grants a Black Heart and changes the Boss Room reward mechanic." },
    { id = 347, cat = "active", name = "Diplopia", en = "Diplopia", tier = "A", icon = "X2", desc = "Duplicates item pedestals and pickups in the current room." },
    { id = 360, cat = "familiar", name = "Incubus", en = "Incubus", tier = "S", icon = "INC", desc = "Copies Isaac's tear attacks as a high-impact offensive familiar.", hot = 1 },
    { id = 698, cat = "familiar", name = "Twisted Pair", en = "Twisted Pair", tier = "S", icon = "TP", desc = "Two demon familiars copy Isaac's shots for substantial extra damage.", hot = 1 },
    { id = 417, cat = "familiar", name = "Succubus", en = "Succubus", tier = "S", icon = "SUC", desc = "A damaging aura attacks enemies and boosts Isaac's damage while inside it.", hot = 1 },
    { id = 387, cat = "familiar", name = "Seraphim", en = "Seraphim", tier = "A", icon = "SER", desc = "Fires high-damage Sacred Heart tears." },
    { id = 268, cat = "familiar", name = "Rotten Baby", en = "Rotten Baby", tier = "A", icon = "ROT", desc = "Spawns attack flies for steady damage." },
    { id = 275, cat = "familiar", name = "Lil Brimstone", en = "Lil Brimstone", tier = "A", icon = "LBR", desc = "Charges and fires a short-range Brimstone laser." },
    { id = 265, cat = "familiar", name = "Dry Baby", en = "Dry Baby", tier = "A", icon = "DRY", desc = "Blocks projectiles and can trigger damage across the entire room." },
    { id = 270, cat = "familiar", name = "Leech", en = "Leech", tier = "A", icon = "LCH", desc = "Chases and bites enemies, healing red hearts when it lands killing blows." },
    { id = 247, cat = "familiar", name = "BFFS!", en = "BFFS!", tier = "A", icon = "BFF", desc = "Increases the size and damage of most familiars." },
    { id = 721, cat = "fun", name = "TMTRAINER", en = "TMTRAINER", tier = "S", icon = "TM", desc = "Turns future items into unpredictable glitch effects for maximum chaos.", hot = 1 },
    { id = 700, cat = "fun", name = "Echo Chamber", en = "Echo Chamber", tier = "S", icon = "EC", desc = "Using consumables repeats earlier consumable effects and can create extreme chains.", hot = 1 },
    { id = 625, cat = "fun", name = "Mega Mush", en = "Mega Mush", tier = "S", icon = "MEG", desc = "Temporarily turns Isaac into a giant that crushes enemies and obstacles.", hot = 1 },
    { id = 330, cat = "fun", name = "Soy Milk", en = "Soy Milk", tier = "A", icon = "SOY", desc = "Greatly lowers damage but massively increases fire rate, creating strong synergy potential." },
    { id = 561, cat = "fun", name = "Almond Milk", en = "Almond Milk", tier = "A", icon = "ALM", desc = "Provides extreme fire rate and gives tears randomized movement patterns." },
    { id = 494, cat = "fun", name = "Jacob's Ladder", en = "Jacob's Ladder", tier = "A", icon = "JL", desc = "Tears release chaining electricity when they hit enemies." },
    { id = 418, cat = "fun", name = "Fruit Cake", en = "Fruit Cake", tier = "A", icon = "FC", desc = "Each tear gains a random special effect." },
    { id = 529, cat = "fun", name = "Pop!", en = "Pop!", tier = "A", icon = "POP", desc = "Tears collide with each other and linger to create dense projectile fields." },
    { id = 570, cat = "fun", name = "Playdough Cookie", en = "Playdough Cookie", tier = "A", icon = "PC", desc = "Tears gain random elemental effects." },
    { id = 233, cat = "fun", name = "Tiny Planet", en = "Tiny Planet", tier = "A", icon = "TP", desc = "Tears orbit Isaac, fundamentally changing how shots travel." },
  },
  commands = {
    { cat = "debug", name = "Invincibility", en = "Debug Flag 3", tier = "S", icon = "INF", desc = "Prevents Isaac from taking damage. Run it again to turn the flag off.", cmd = "debug 3" },
    { cat = "debug", name = "Extreme Damage", en = "Debug Flag 4", tier = "S", icon = "DMG", desc = "Grants extreme damage for quickly testing rooms and bosses.", cmd = "debug 4" },
    { cat = "debug", name = "Unlimited Charge", en = "Debug Flag 8", tier = "S", icon = "CHG", desc = "Gives active items unlimited charge. Run it again to turn the flag off.", cmd = "debug 8" },
    { cat = "debug", name = "Extreme Luck", en = "Debug Flag 9", tier = "A", icon = "LCK", desc = "Raises luck to an extreme value for testing luck-based effects.", cmd = "debug 9" },
    { cat = "debug", name = "Quick Kill", en = "Debug Flag 10", tier = "A", icon = "KIL", desc = "Makes enemies die quickly. Run it again to turn the flag off.", cmd = "debug 10" },
    { cat = "debug", name = "Show Hitboxes", en = "Debug Flag 6", tier = "A", icon = "HIT", desc = "Displays entity collision areas for movement and projectile testing.", cmd = "debug 6" },
    { cat = "debug", name = "Show Damage Values", en = "Debug Flag 7", tier = "A", icon = "NUM", desc = "Displays damage numbers and related diagnostic information.", cmd = "debug 7" },
    { cat = "debug", name = "Show Room Info", en = "Debug Flag 5", tier = "A", icon = "RM", desc = "Displays diagnostic information about the current room.", cmd = "debug 5" },
    { cat = "supply", name = "99 Coins", en = "A Dollar", tier = "S", icon = "$", desc = "Uses A Dollar to grant a large amount of coins. The resource grant comes from ItemConfig and is not reversed by removing the item.", cmd = "giveitem c18" },
    { cat = "supply", name = "99 Keys", en = "Skeleton Key", tier = "S", icon = "KEY", desc = "Uses Skeleton Key to grant a large amount of keys. The resource grant comes from ItemConfig and is not reversed by removing the item.", cmd = "giveitem c17" },
    { cat = "supply", name = "99 Bombs", en = "Pyro", tier = "S", icon = "BMB", desc = "Uses Pyro to grant a large amount of bombs. The resource grant comes from ItemConfig and is not reversed by removing the item.", cmd = "giveitem c190" },
    { cat = "supply", name = "Spawn Soul Heart", en = "Soul Heart", tier = "A", icon = "HP", desc = "Spawns one Soul Heart near Isaac.", cmd = "spawn 5.10.3" },
    { cat = "supply", name = "Spawn Eternal Heart", en = "Eternal Heart", tier = "A", icon = "EHP", desc = "Spawns one Eternal Heart near Isaac.", cmd = "spawn 5.10.4" },
    { cat = "supply", name = "Spawn Golden Chest", en = "Golden Chest", tier = "A", icon = "CH", desc = "Spawns one Golden Chest near Isaac.", cmd = "spawn 5.50.1" },
    { cat = "supply", name = "Spawn Random Item", en = "Random Pedestal", tier = "A", icon = "?", desc = "Spawns a random collectible pedestal near Isaac.", cmd = "spawn 5.100.0" },
    { cat = "supply", name = "Kill Room", en = "Kill Room", tier = "A", icon = "KIL", desc = "Immediately kills enemies in the current room.", cmd = "kill" },
    -- Normal/Hard mode floor whitelist. Do not generate arbitrary suffixes:
    -- the native stage command may crash on nonexistent stage/type pairs.
    { cat = "stage", name = "Basement I", en = "Basement I", tier = "A", icon = "1", desc = "Warp to Basement I.", cmd = "stage 1" },
    { cat = "stage", name = "Cellar I", en = "Cellar I", tier = "A", icon = "1a", desc = "Warp to Cellar I.", cmd = "stage 1a" },
    { cat = "stage", name = "Burning Basement I", en = "Burning Basement I", tier = "A", icon = "1b", desc = "Warp to Burning Basement I.", cmd = "stage 1b" },
    { cat = "stage", name = "Downpour I", en = "Downpour I", tier = "S", icon = "1c", desc = "Warp to Downpour I on the Repentance alternate path.", cmd = "stage 1c" },
    { cat = "stage", name = "Dross I", en = "Dross I", tier = "S", icon = "1d", desc = "Warp to Dross I on the Repentance alternate path.", cmd = "stage 1d" },
    { cat = "stage", name = "Basement II", en = "Basement II", tier = "A", icon = "2", desc = "Warp to Basement II.", cmd = "stage 2" },
    { cat = "stage", name = "Cellar II", en = "Cellar II", tier = "A", icon = "2a", desc = "Warp to Cellar II.", cmd = "stage 2a" },
    { cat = "stage", name = "Burning Basement II", en = "Burning Basement II", tier = "A", icon = "2b", desc = "Warp to Burning Basement II.", cmd = "stage 2b" },
    { cat = "stage", name = "Downpour II", en = "Downpour II", tier = "S", icon = "2c", desc = "Warp to Downpour II on the Repentance alternate path.", cmd = "stage 2c" },
    { cat = "stage", name = "Dross II", en = "Dross II", tier = "S", icon = "2d", desc = "Warp to Dross II on the Repentance alternate path.", cmd = "stage 2d" },
    { cat = "stage", name = "Caves I", en = "Caves I", tier = "A", icon = "3", desc = "Warp to Caves I.", cmd = "stage 3" },
    { cat = "stage", name = "Catacombs I", en = "Catacombs I", tier = "A", icon = "3a", desc = "Warp to Catacombs I.", cmd = "stage 3a" },
    { cat = "stage", name = "Flooded Caves I", en = "Flooded Caves I", tier = "A", icon = "3b", desc = "Warp to Flooded Caves I.", cmd = "stage 3b" },
    { cat = "stage", name = "Mines I", en = "Mines I", tier = "S", icon = "3c", desc = "Warp to Mines I on the Repentance alternate path.", cmd = "stage 3c" },
    { cat = "stage", name = "Ashpit I", en = "Ashpit I", tier = "S", icon = "3d", desc = "Warp to Ashpit I on the Repentance alternate path.", cmd = "stage 3d" },
    { cat = "stage", name = "Caves II", en = "Caves II", tier = "A", icon = "4", desc = "Warp to Caves II.", cmd = "stage 4" },
    { cat = "stage", name = "Catacombs II", en = "Catacombs II", tier = "A", icon = "4a", desc = "Warp to Catacombs II.", cmd = "stage 4a" },
    { cat = "stage", name = "Flooded Caves II", en = "Flooded Caves II", tier = "A", icon = "4b", desc = "Warp to Flooded Caves II.", cmd = "stage 4b" },
    { cat = "stage", name = "Mines II", en = "Mines II", tier = "S", icon = "4c", desc = "Warp to Mines II on the Repentance alternate path.", cmd = "stage 4c" },
    { cat = "stage", name = "Ashpit II", en = "Ashpit II", tier = "S", icon = "4d", desc = "Warp to Ashpit II on the Repentance alternate path.", cmd = "stage 4d" },
    { cat = "stage", name = "Depths I", en = "Depths I", tier = "A", icon = "5", desc = "Warp to Depths I.", cmd = "stage 5" },
    { cat = "stage", name = "Necropolis I", en = "Necropolis I", tier = "A", icon = "5a", desc = "Warp to Necropolis I.", cmd = "stage 5a" },
    { cat = "stage", name = "Dank Depths I", en = "Dank Depths I", tier = "A", icon = "5b", desc = "Warp to Dank Depths I.", cmd = "stage 5b" },
    { cat = "stage", name = "Mausoleum I", en = "Mausoleum I", tier = "S", icon = "5c", desc = "Warp to Mausoleum I on the Repentance alternate path.", cmd = "stage 5c" },
    { cat = "stage", name = "Gehenna I", en = "Gehenna I", tier = "S", icon = "5d", desc = "Warp to Gehenna I on the Repentance alternate path.", cmd = "stage 5d" },
    { cat = "stage", name = "Depths II", en = "Depths II", tier = "A", icon = "6", desc = "Warp to Depths II, where Mom is fought.", cmd = "stage 6" },
    { cat = "stage", name = "Necropolis II", en = "Necropolis II", tier = "A", icon = "6a", desc = "Warp to Necropolis II.", cmd = "stage 6a" },
    { cat = "stage", name = "Dank Depths II", en = "Dank Depths II", tier = "A", icon = "6b", desc = "Warp to Dank Depths II.", cmd = "stage 6b" },
    { cat = "stage", name = "Mausoleum II", en = "Mausoleum II", tier = "S", icon = "6c", desc = "Warp to Mausoleum II on the Repentance alternate path.", cmd = "stage 6c" },
    { cat = "stage", name = "Gehenna II", en = "Gehenna II", tier = "S", icon = "6d", desc = "Warp to Gehenna II on the Repentance alternate path.", cmd = "stage 6d" },
    { cat = "stage", name = "Womb I", en = "Womb I", tier = "A", icon = "7", desc = "Warp to Womb I.", cmd = "stage 7" },
    { cat = "stage", name = "Utero I", en = "Utero I", tier = "A", icon = "7a", desc = "Warp to Utero I.", cmd = "stage 7a" },
    { cat = "stage", name = "Scarred Womb I", en = "Scarred Womb I", tier = "A", icon = "7b", desc = "Warp to Scarred Womb I.", cmd = "stage 7b" },
    { cat = "stage", name = "Corpse I", en = "Corpse I", tier = "S", icon = "7c", desc = "Warp to Corpse I on the Repentance alternate path.", cmd = "stage 7c" },
    { cat = "stage", name = "Womb II", en = "Womb II", tier = "A", icon = "8", desc = "Warp to Womb II.", cmd = "stage 8" },
    { cat = "stage", name = "Utero II", en = "Utero II", tier = "A", icon = "8a", desc = "Warp to Utero II.", cmd = "stage 8a" },
    { cat = "stage", name = "Scarred Womb II", en = "Scarred Womb II", tier = "A", icon = "8b", desc = "Warp to Scarred Womb II.", cmd = "stage 8b" },
    { cat = "stage", name = "Corpse II", en = "Corpse II", tier = "S", icon = "8c", desc = "Warp to Corpse II on the Repentance alternate path.", cmd = "stage 8c" },
    { cat = "stage", name = "Blue Womb", en = "Blue Womb", tier = "S", icon = "9", desc = "Warp to Blue Womb, where Hush is fought.", cmd = "stage 9" },
    { cat = "stage", name = "Sheol", en = "Sheol", tier = "A", icon = "10", desc = "Warp to Sheol.", cmd = "stage 10" },
    { cat = "stage", name = "Cathedral", en = "Cathedral", tier = "A", icon = "10a", desc = "Warp to Cathedral.", cmd = "stage 10a" },
    { cat = "stage", name = "Dark Room", en = "Dark Room", tier = "A", icon = "11", desc = "Warp to Dark Room.", cmd = "stage 11" },
    { cat = "stage", name = "The Chest", en = "The Chest", tier = "A", icon = "11a", desc = "Warp to The Chest.", cmd = "stage 11a" },
    { cat = "stage", name = "The Void", en = "The Void", tier = "S", icon = "12", desc = "Warp to The Void, where Delirium can be fought.", cmd = "stage 12" },
    { cat = "stage", name = "Home", en = "Home", tier = "S", icon = "13", desc = "Warp to Home on the final Repentance route.", cmd = "stage 13" },
    -- Greed and Greedier use a separate, documented stage 1-7 progression.
    -- Do not add suffixes or stage 8+: those are not part of the public Greed route.
    { cat = "stage", name = "Basement (Greed)", stageMode = "greed", en = "Basement (Greed)", tier = "A", icon = "G1", desc = "Warp to the Basement floor in Greed mode.", cmd = "stage 1" },
    { cat = "stage", name = "Caves (Greed)", stageMode = "greed", en = "Caves (Greed)", tier = "A", icon = "G2", desc = "Warp to the Caves floor in Greed mode.", cmd = "stage 2" },
    { cat = "stage", name = "Depths (Greed)", stageMode = "greed", en = "Depths (Greed)", tier = "A", icon = "G3", desc = "Warp to the Depths floor in Greed mode.", cmd = "stage 3" },
    { cat = "stage", name = "Womb (Greed)", stageMode = "greed", en = "Womb (Greed)", tier = "A", icon = "G4", desc = "Warp to the Womb floor in Greed mode.", cmd = "stage 4" },
    { cat = "stage", name = "Sheol (Greed)", stageMode = "greed", en = "Sheol (Greed)", tier = "A", icon = "G5", desc = "Warp to the Sheol floor in Greed mode.", cmd = "stage 5" },
    { cat = "stage", name = "The Shop (Greed)", stageMode = "greed", en = "The Shop (Greed)", tier = "S", icon = "G6", desc = "Warp to The Shop in Greed mode.", cmd = "stage 6" },
    { cat = "stage", name = "Ultra Greed", stageMode = "greed", en = "Ultra Greed", tier = "S", icon = "G7", desc = "Warp to the Ultra Greed floor.", cmd = "stage 7" },
  },
}
